---
apiVersion: v1
kind: Namespace
metadata:
  name: mlb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: mlb
spec:
  interval: 1m0s
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: mlb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: "*"
      interval: 12h
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.250-192.168.1.254

