---
apiVersion: v1
kind: Namespace
metadata:
  name: rflctr
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: reflector
  namespace: rflctr
spec:
  interval: 24h
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: rflctr
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: rflctr
      interval: 12h
  # values:

