---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook
  namespace: storage
spec:
  interval: 30m0s
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rookceph
  namespace: storage
spec:
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: storage
      version: 1.11.2
  interval: 30m0s
  releaseName: rookceph
  targetNamespace: storage
  values:
    monitoring:
      enabled: true
    enableDiscoveryDaemon: true
    csi:
      kubeletDirPath: /var/lib/k0s/kubelet

